
public enum TownName {
	WYLHIEN, USSELEN, YTTAR, GRANGOR, MAHDAVIKIA,
	PARUNDIA, KIHROMAH, JXARA, DAGAMURA, ALBARAN,
	JACCARANDA, THROTMANNI, FEODOR, LAPPHALYA,
	VIRST, STRYKHAVEN, ELVENHOLD, ERGEREN, RIVINIA, 
	TICHIH, BEATA, CICBIB, CBROTMANNI, DABDAVIKIA, KIBROMAB, DARUNDIA
	
}
