package gamelogic;

public enum GamePhase {
	DRAWTRAVELCARDSONE,
	DRAWTRAVELCARDSTWO,
	DRAWTRAVELCARDSTHREE,
	DRAWTOKENSANDCOUNTERS,
	DRAWFACEUPCOUNTERONE,
	DRAWFACEUPCOUNTERTWO,
	DRAWFACEUPCOUNTERTHREE,
	AUCTION,
	PLANTRAVEL,
	MOVEBOOT,
	CHOOSECARDSTOKEEP,
	DRAWCARDAFTERTRAVELONE,
	DRAWCARDAFTERTRAVELTWO,
	FINISHROUND
}
